name: sigser_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  awesome_dialog: ^3.2.1
  flutter_dotenv: ^5.0.2


flutter:
  uses-material-design: true
  assets:
  - assets/
  - .env
