name: sigser_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_stripe: ^11.3.0
  font_awesome_flutter: ^10.8.0
  image: ^4.3.0
  image_input: ^0.0.5
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2
  mqtt_client: ^10.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  awesome_dialog: ^3.2.1
  flutter_dotenv: ^5.0.2


flutter:
  uses-material-design: true
  assets:
  - assets/
  - .env
